---

- name: create dir for facts
  file:
    path: /etc/ansible/facts.d
    state: directory
  become: yes          

- name: Installing necessaries packets
  apt:
    name: '{{ packages }}'
    state: present
    update_cache: yes
  notify: enable and start time service
  become: yes
