---

- name: enable and restart ufw service   
  service: name=ufw enabled=yes state=restarted   
  become: yes

- name: save fact
  copy:
    content: |
      {
        "version": "{{ ufw_version.stdout }}",
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/ufw.fact
  become: yes
